import React from "react";
import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const Layout = (props: any) => {
  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Dream It</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpg" />
        
      </Head>
      <Header />
      <main className="flex-grow">{props.children}</main>
      <Footer />
      <ToastContainer />
    </div>
  );
};

export default Layout;
